
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_jhx?serverTimezone=UTC
    username: root
    password: admin123


mybatis-plus:
  global-config:
    db-config:
      table-prefix: tbl_
